name: build

on:
  release:
    types:
      - published

jobs:
  build:
    name: build wheel
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install Python
        uses: actions/setup-python@v2
      - name: install dependencies on Linux
        run: sudo apt install libboost-all-dev libeigen3-dev
      - name: build wheel
        run: pip wheel . -w dist --no-deps
      - name: save wheel
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./dist/*.whl
  package:
    name: package source
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: install Python
        uses: actions/setup-python@v2
      - name: install dependencies
        run: pip install dunamai
      - name: package source
        run: python setup.py sdist
      - name: save source package
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./dist/*.tar.gz
  deploy:
    name: publish to PyPI
    needs: [ build_wheels, build_sdist ]
    runs-on: ubuntu-latest
    steps:
      - name: retrieve wheel(s) and source
        uses: actions/download-artifact@v2
        with:
          name: build
          path: dist
      - name: upload wheel(s) and source
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
